version: '2'
services:

    web:
        image: showroute

    nginx:
        restart: always
        image: nginx:latest
        ports:
            - "80:80"
        links:
            - web:web
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf


