version: '2'
services:

    chat:
        image: showroute

    auth:
        image: showroute

    nginx:
        restart: always
        image: nginx:latest
        ports:
            - "80:80"
        links:
            - auth:auth
            - chat:chat
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf


